import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Separate sidebars for each root folder.
 * Each folder shows only its own content.
 */
const sidebars: SidebarsConfig = {
  technologySidebar: [{
    type: 'autogenerated',
    dirName: 'Technology',
  }],
  financeSidebar: [{
    type: 'autogenerated',
    dirName: 'Finance',
  }],
  generalSidebar: [{
    type: 'autogenerated',
    dirName: 'General',
  }],
};

export default sidebars;
