import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebars for each root folder
 * Each folder shows only its own content
 */
const sidebars: SidebarsConfig = {
  technologySidebar: [{
    type: 'autogenerated',
    dirName: 'Technology',
  }],
  financeSidebar: [{
    type: 'autogenerated',
    dirName: 'Finance',
  }],
  personalDevelopmentSidebar: [{
    type: 'autogenerated',
    dirName: 'Personal-Development',
  }],
  referenceSidebar: [{
    type: 'autogenerated',
    dirName: 'reference',
  }],
  aiSidebar: [{
    type: 'autogenerated',
    dirName: 'Artificial Intelligence - 15 min notes',
  }],
};

export default sidebars;
